apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: kube-prometheus-stack  
spec:
  secretName: grafana-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana-justpay.duckdns.org
  dnsNames:
  - grafana-justpay.duckdns.org
