apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarqube-cert
  namespace: sonarqube  
spec:
  secretName: sonarqube-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sonarqube-justpay.duckdns.org
  dnsNames:
  - sonarqube-justpay.duckdns.org
