apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  namespace: justpay
  labels:
    project: justpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
        project: justpay
    spec:
      containers:
        - name: crm
          image: justpayacrAKS1.azurecr.io/crm:latest
          # env:
          #   - name: RABBITMQ_IP
          #     value: "rabbitmq.rabbitmq.svc.cluster.local"
          #   - name: RABBITMQ_PORT
          #     value: "5671"
          #   - name: RABBITMQ_USERNAME
          #     value: "user"
          #   - name: RABBITMQ_PASSWORD
          #     value: "justpay"
          ports:
            - containerPort: 5000
      # imagePullSecrets:
      #   - name: macr-auth  # Only needed for non-AKS clusters
---
