apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: justpay
  labels:
    project: justpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        project: justpay
    spec:
      containers:
        - name: identity
          image: justpayacrAKS1.azurecr.io/identity:latest
          ports:
            - containerPort: 3000

---

