apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: justpay
  labels:
    project: justpay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
        project: justpay
    spec:
      containers:
        - name: identity
          image: justpay.azurecr.io/identity:latest
          ports:
            - containerPort: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
      imagePullSecrets:
        - name: eacr-auth
---

