apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: justpay
  labels:
    project: justpay
spec:
  selector:
    app: identity
  ports:
    - name: identityport
      port: 80
      targetPort: 3000